name: gps_tracking_flutter
description: Aplicación de monitoreo y rastreo GPS con geocercas y alertas.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.2
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  network_info_plus: ^5.0.3
  socket_io_client: ^2.0.3+1

  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_map: ^6.1.0

  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2  # Cambiar esta línea
  geolocator: ^11.0.0
  location: ^5.0.3
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.0.15
  intl: ^0.18.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/